"""
Tests for TaxFi PDF generation.

Verifies that ReportLab generates valid PDFs for:
- Form 8949 (short-term and long-term transactions)
- Schedule D (capital gains summary)
- Tax summary (plain-English with onchain hashes)
"""

from __future__ import annotations

import pytest


def test_generate_form_8949_pdf():
    """Form 8949 PDF should be generated with valid PDF structure."""
    from backend.utils.pdf_generator import generate_form_8949

    short_term = [
        {
            "description": "0.5 ETH",
            "acquisition_date": "2025-01-15",
            "sale_date": "2025-06-01",
            "proceeds": 1500.00,
            "cost_basis": 1000.00,
            "gain_loss": 500.00,
        },
    ]

    long_term = [
        {
            "description": "1.0 BTC",
            "acquisition_date": "2023-01-10",
            "sale_date": "2025-08-01",
            "proceeds": 60000.00,
            "cost_basis": 30000.00,
            "gain_loss": 30000.00,
        },
    ]

    pdf_bytes = generate_form_8949(
        user_address="0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18",
        tax_year=2025,
        short_term_entries=short_term,
        long_term_entries=long_term,
    )

    assert len(pdf_bytes) > 500, "PDF should have substantial content"
    assert pdf_bytes.startswith(b"%PDF"), "Should start with PDF magic bytes"
    assert b"ReportLab" in pdf_bytes, "Should be generated by ReportLab"
    # Note: PDF content is compressed by ReportLab, so text assertions check the magic header only


def test_generate_form_8949_empty():
    """Form 8949 should handle zero transactions gracefully."""
    from backend.utils.pdf_generator import generate_form_8949

    pdf_bytes = generate_form_8949(
        user_address="0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18",
        tax_year=2025,
        short_term_entries=[],
        long_term_entries=[],
    )

    assert len(pdf_bytes) > 300, "PDF should have content even with no transactions"
    assert pdf_bytes.startswith(b"%PDF")
    assert b"ReportLab" in pdf_bytes


def test_generate_schedule_d():
    """Schedule D PDF should be generated with valid PDF structure."""
    from backend.utils.pdf_generator import generate_schedule_d

    pdf_bytes = generate_schedule_d(
        user_address="0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18",
        tax_year=2025,
        short_term_gain=5000.0,
        short_term_loss=1000.0,
        long_term_gain=30000.0,
        long_term_loss=2000.0,
    )

    assert len(pdf_bytes) > 400
    assert pdf_bytes.startswith(b"%PDF")
    assert b"ReportLab" in pdf_bytes


def test_generate_tax_summary():
    """Tax summary PDF should include onchain hashes reference."""
    from backend.utils.pdf_generator import generate_tax_summary

    summary = {
        "summary": "Your 2025 tax summary.",
        "key_numbers": {
            "net_capital_gain": "$34,000",
            "estimated_tax": "$8,800",
        },
    }

    onchain_hashes = {
        "form_8949": "0xabc123def456",
        "schedule_d": "0x789abc012def",
    }

    pdf_bytes = generate_tax_summary(
        user_address="0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18",
        tax_year=2025,
        summary=summary,
        onchain_hashes=onchain_hashes,
    )

    assert len(pdf_bytes) > 400
    assert pdf_bytes.startswith(b"%PDF")
    assert b"ReportLab" in pdf_bytes


def test_generate_all_forms():
    """generate_all_forms should return a dict of valid PDFs."""
    from backend.utils.pdf_generator import generate_all_forms

    form_data = {
        "form_8949": {
            "parts": {
                "I": {"transactions": []},
                "II": {"transactions": []},
            }
        },
        "schedule_d": {
            "part_i": {"total_gain": 5000.0, "total_loss": 1000.0},
            "part_ii": {"total_gain": 30000.0, "total_loss": 2000.0},
        },
        "summary": {
            "summary": "Your 2025 tax summary.",
            "key_numbers": {"net_capital_gain": "$32,000"},
        },
    }

    onchain_hashes = {"form_8949": "0xabc123"}

    pdfs = generate_all_forms(
        user_address="0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18",
        tax_year=2025,
        form_data=form_data,
        onchain_hashes=onchain_hashes,
    )

    assert "form_8949.pdf" in pdfs
    assert "schedule_d.pdf" in pdfs
    assert "tax_summary.pdf" in pdfs

    for name, content in pdfs.items():
        assert len(content) > 300, f"{name} should have content"
        assert content.startswith(b"%PDF"), f"{name} should be a valid PDF"
