'use client';

export default function Footer() {
  const footerLinks = {
    Product: ['How It Works', 'Features', 'Pricing', 'FAQ'],
    Resources: ['Documentation', 'API Reference', 'Changelog', 'Status'],
    Legal: ['Privacy Policy', 'Terms of Service', 'Cookie Policy', 'Contact'],
  };

  return (
    <footer className="border-t border-gray-200/50 bg-white/50 backdrop-blur-xl py-16">
      <div className="max-w-7xl mx-auto px-6">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center text-xs font-bold text-white shadow-lg">
                T
              </div>
              <span className="text-lg font-bold text-gray-900">
                Tax<span className="text-emerald-500">Fi</span>
              </span>
            </div>
            <p className="text-sm text-gray-600 leading-relaxed max-w-xs">
              Your crypto tax agent that pays for itself. Non-custodial,
              privacy-first, gasless.
            </p>
          </div>

          {/* Link Columns */}
          {Object.entries(footerLinks).map(([title, links]) => (
            <div key={title}>
              <h4 className="text-sm font-semibold text-gray-900 mb-4">{title}</h4>
              <div className="flex flex-col gap-3">
                {links.map((link) => (
                  <a
                    key={link}
                    href={title === 'Product' ? `#${link.toLowerCase().replace(/\s+/g, '-')}` : '#'}
                    className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
                  >
                    {link}
                  </a>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="pt-8 border-t border-gray-200/50 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-gray-500">
            &copy; {new Date().getFullYear()} TaxFi. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            {['Twitter', 'Discord', 'Docs', 'Blog'].map((label, i) => (
              <a
                key={i}
                href="#"
                className="text-xs text-gray-500 hover:text-gray-900 bg-white/60 backdrop-blur-xl hover:bg-white/80 px-3 py-1.5 rounded-lg border border-gray-200/50 transition-colors font-medium shadow-sm"
              >
                {label}
              </a>
            ))}
          </div>
        </div>

        <p className="text-[10px] text-gray-400 mt-6 text-center max-w-2xl mx-auto leading-relaxed">
          TaxFi is not a CPA, tax attorney, or financial advisor. The information,
          calculations, and forms generated by TaxFi are for informational purposes
          only and should be reviewed by a qualified tax professional before filing.
          Crypto tax laws vary by jurisdiction and are subject to change.
        </p>
      </div>
    </footer>
  );
}
