'use client';

export default function Footer() {
  const footerLinks = {
    Product: ['How It Works', 'Features', 'Pricing', 'FAQ'],
    Resources: ['Documentation', 'API Reference', 'Changelog', 'Status'],
    Legal: ['Privacy Policy', 'Terms of Service', 'Cookie Policy', 'Contact'],
  };

  return (
    <footer className="border-t border-gray-200/50 bg-white/50 backdrop-blur-xl py-16">
      <div className="max-w-7xl mx-auto px-6">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
          {/* Brand */}
          <div>
            <a href="#" className="flex items-center gap-3 mb-4 group">
              <div className="relative w-8 h-8">
                <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-500 opacity-20 blur-md group-hover:opacity-30 transition-opacity" />
                <div className="relative w-8 h-8 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center text-xs font-bold text-white shadow-lg">
                  T
                </div>
              </div>
              <span className="text-lg font-bold text-gray-900">
                Tax<span className="text-emerald-500">Fi</span>
              </span>
            </a>
            <p className="text-sm text-gray-500 leading-relaxed max-w-xs">
              Your crypto tax agent that pays for itself. Non-custodial, privacy-first, gasless.
            </p>
          </div>

          {/* Link Columns */}
          {Object.entries(footerLinks).map(([title, links]) => (
            <div key={title}>
              <h4 className="text-sm font-semibold text-gray-900 mb-4">{title}</h4>
              <div className="flex flex-col gap-3">
                {links.map((link) => (
                  <a
                    key={link}
                    href={title === 'Product' ? `#${link.toLowerCase().replace(/\s+/g, '-')}` : '#'}
                    className="text-sm text-gray-500 hover:text-emerald-600 transition-colors duration-300 w-fit"
                  >
                    {link}
                  </a>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="pt-8 border-t border-gray-200/50 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-gray-400">
            &copy; {new Date().getFullYear()} TaxFi. All rights reserved.
          </p>
          <div className="flex items-center gap-3">
            {['Twitter', 'Discord', 'GitHub', 'Blog'].map((label) => (
              <a
                key={label}
                href="#"
                className="text-xs text-gray-400 hover:text-emerald-600 bg-white/60 backdrop-blur-xl hover:bg-emerald-50 px-3 py-1.5 rounded-lg border border-gray-200/50 transition-all duration-300 font-medium shadow-sm"
              >
                {label}
              </a>
            ))}
          </div>
        </div>

        <p className="text-[10px] text-gray-400 mt-6 text-center max-w-2xl mx-auto leading-relaxed">
          TaxFi is not a CPA, tax attorney, or financial advisor. The information,
          calculations, and forms generated by TaxFi are for informational purposes
          only and should be reviewed by a qualified tax professional before filing.
          Crypto tax laws vary by jurisdiction and are subject to change.
        </p>
      </div>
    </footer>
  );
}
